name: FormPeak

options:
  bundleIdPrefix: com.artkriukov
  deploymentTarget:
    iOS: "17.0"
  defaultConfig: Production

configs:
  Debug: debug
  Production: release
  
packages:
  SwiftLint:
    url: https://github.com/realm/SwiftLint
    from: 0.59.0
  Rswift:
    url: https://github.com/mac-cain13/R.swift.git
    from: 7.0.0

targets:
  FormPeak:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: "17.0"
    sources:
      - path: FormPeak/
    resources:
      - path: FormPeak/Resources
    info:
      path: FormPeak/Resources/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchStoryboardName: LaunchScreen
    settings:
      base:
        INFOPLIST_FILE: FormPeak/Resources/Info.plist
        UILaunchStoryboardName: LaunchScreen
        PRODUCT_BUNDLE_IDENTIFIER: com.artkriukov.FormPeak
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.0"
        VERSIONING_SYSTEM: "apple-generic"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        SUPPORTED_INTERFACE_ORIENTATIONS: "UIInterfaceOrientationPortrait"
    scheme:
      environmentVariables:
        DYLD_PRINT_STATISTICS: "1"
    dependencies:
      - package: Rswift
        product: RswiftLibrary

    buildToolPlugins:
      - plugin: RswiftGenerateInternalResources
        package: Rswift

    postCompileScripts:
      - name: SwiftLint
        runOnlyWhenInstalling: false
        script: |
          cd "$SRCROOT"
          if [[ "$(uname -m)" == "arm64" ]]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi
          echo "SwiftLint working dir: $(pwd)"
          if command -v swiftlint >/dev/null 2>&1; then
            swiftlint --config "$SRCROOT/.swiftlint.yml"
          else
            echo "warning: swiftlint not found - see https://github.com/realm/SwiftLint#installation"
          fi